In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [3]:
lst

[1, 2, 3, 4, 5]

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [28]:
lst1=[2,3,4,5,5]
lst2=[3,4,5,6,7]
lst3=[4,5,6,7,7]
arr=np.array([lst1,lst2,lst3])

In [8]:
arr

array([[2, 3, 4, 5, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 7]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr.reshape(5,3)

array([[2, 3, 4],
       [5, 5, 3],
       [4, 5, 6],
       [7, 4, 5],
       [6, 7, 7]])

In [11]:
arr.shape

(3, 5)

### indexing

In [25]:
arr=np.array([1,2,3,4,5,6,7,8])

In [26]:
arr[4]

5

In [20]:
arr[3:]=100

In [21]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100])

In [29]:
arr[:,:]

array([[2, 3, 4, 5, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 7]])

In [30]:
arr[1:2,2:3]

array([[5]])

In [12]:
arr

array([[2, 3, 4, 5, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 7]])

In [23]:
arr= np.arange(0,10,step=2)

In [24]:
arr

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])